export { default as About } from './about'
export { default as Contact } from './contact'
export { default as Footer } from './footer'
export { default as Header } from './header'
export { default as Navbar } from './navbar'
export { default as Skills } from './skills'
export { default as Work } from './work'
